name: Build Kashmir Meeqat APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign Release APK
      if: ${{ secrets.SIGNING_KEY != '' }}
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: Kashmir-Meeqat-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: Kashmir-Meeqat-Release
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Upload Signed APK (if signing succeeded)
      if: steps.sign_app.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: Kashmir-Meeqat-Signed
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        retention-days: 30
        
    - name: Create Release Info
      run: |
        echo "# Kashmir Meeqat APK Build" > build-info.md
        echo "" >> build-info.md
        echo "**Build Date:** $(date)" >> build-info.md
        echo "**Commit:** ${{ github.sha }}" >> build-info.md
        echo "" >> build-info.md
        echo "## Available Downloads:" >> build-info.md
        echo "- **Debug APK:** For testing and development" >> build-info.md
        echo "- **Release APK:** Optimized for production use" >> build-info.md
        echo "" >> build-info.md
        echo "## Installation Instructions:" >> build-info.md
        echo "1. Download the APK file" >> build-info.md
        echo "2. Enable 'Install from Unknown Sources' on your Android device" >> build-info.md
        echo "3. Install the APK" >> build-info.md
        echo "4. Grant location and notification permissions" >> build-info.md
        echo "5. Enjoy accurate prayer times for Kashmir!" >> build-info.md
        
    - name: Upload Build Info
      uses: actions/upload-artifact@v3
      with:
        name: Build-Info
        path: build-info.md
        retention-days: 30